"""IngestionRunner — executes data pipelines and writes results to LanceDB.

Pipeline code (generated by Claude) runs in a subprocess sandbox.
Has WRITE access to LanceDB (unlike QueryEngine which is read-only).
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile

import modal
from .app import app, image
from . import lancedb_store
from .security import check_pipeline_code


@app.cls(
    image=image,
    secrets=[modal.Secret.from_name("agentboard-s3")],
    timeout=300,  # 5 minute max per pipeline
)
class IngestionRunner:
    """Runs data pipelines in sandboxed subprocesses."""

    @modal.enter()
    def setup(self):
        self.db = lancedb_store.connect()

    @modal.method()
    def run_pipeline(
        self,
        dashboard_id: str,
        widget_id: str,
        code: str,
        params: dict | None = None,
    ) -> dict:
        """Execute a pipeline and write results to LanceDB.

        Args:
            dashboard_id: Dashboard that owns this widget
            widget_id: Target widget
            code: Python function body that returns list[dict]
            params: Parameters passed to the function

        Returns:
            {"status": "ok", "rows": N} or {"status": "error", "message": "..."}
        """
        # Security check — reject dangerous code before execution
        check_pipeline_code(code)

        # Wrap the user code in a runner script
        runner_code = f"""
import json
import sys

params = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {{}}

def fetch(params):
{_indent(code, 4)}

result = fetch(params)
print(json.dumps(result))
"""

        try:
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".py", delete=False
            ) as f:
                f.write(runner_code)
                f.flush()

                result = subprocess.run(
                    [sys.executable, f.name, json.dumps(params or {})],
                    capture_output=True,
                    text=True,
                    timeout=120,
                )

            if result.returncode != 0:
                return {
                    "status": "error",
                    "message": result.stderr[:500],
                }

            data = json.loads(result.stdout)

            if not isinstance(data, list):
                return {
                    "status": "error",
                    "message": "Pipeline must return a list of dicts",
                }

            lancedb_store.write_widget_data(
                self.db, dashboard_id, widget_id, data
            )

            return {"status": "ok", "rows": len(data)}

        except subprocess.TimeoutExpired:
            return {"status": "error", "message": "Pipeline timed out (120s)"}
        except json.JSONDecodeError:
            return {
                "status": "error",
                "message": "Pipeline output is not valid JSON",
            }
        except Exception as e:
            return {"status": "error", "message": str(e)[:500]}

    @modal.method()
    def run_all_pipelines(self, dashboard_id: str) -> list[dict]:
        """Run all pipelines for a dashboard (used during refresh)."""
        spec = lancedb_store.get_dashboard(self.db, dashboard_id)
        if not spec:
            return [{"status": "error", "message": "Dashboard not found"}]

        results = []
        for widget in spec.get("widgets", []):
            ds = widget.get("dataSource", {})
            if ds.get("type") == "modal_endpoint" and ds.get("endpoint"):
                # Pipeline code is stored in the endpoint field as a reference
                # In production, this would load the pipeline code from storage
                results.append({
                    "widget_id": widget["id"],
                    "status": "skipped",
                    "message": "Pipeline execution via endpoint reference",
                })
            elif ds.get("type") == "static":
                # Static data doesn't need refresh
                results.append({
                    "widget_id": widget["id"],
                    "status": "skipped",
                    "message": "Static data",
                })
        return results


def _indent(code: str, spaces: int) -> str:
    """Indent each line of code by N spaces."""
    prefix = " " * spaces
    return "\n".join(prefix + line for line in code.splitlines())
